### ISSUE TITLE
A few more function ideas

### ISSUE THREAD

**Issue by daattali** [MangoTheCat/shinytest#14]
I played with shinytest for a bit and it looks very promising, works well so far with the basic stuff I tried testing.  Just a few more function ideas that I think could be useful:

-  app$update_value(id, value)
- app$click(id/selector)
- app$isElementVisible(element)

I also wasn't 100% sure what `send_keys` does, does it send **keyboard** keypresses? If that's the case, it could be clarified.  Would love to play around with this package some more later

**Comment by gaborcsardi** [comment]
> app$update_value(id, value)

So that would be a `find_widget` and a `set_value`, right.

> app$click(id/selector)

What is `id/selector`? A shiny widget and/or a CSS selector? 

> app$isElementVisible(element)

What is element? And what do you mean by visible? Can the user see it on the screen without scrolling?

> I also wasn't 100% sure what send_keys does, does it send keyboard keypresses? If that's the case, it could be clarified. 

Agreed. Yes, it sends keypresses. You can send special keys as well. I have only used to type into an input field so far, so yes, I'll need to test it, and document it, both for `webdriver` and `shinytest` https://github.com/MangoTheCat/webdriver/issues/25

**Comment by daattali** [comment]
- app$update_value() - yes, I personally would find it much simpler to have a single function for it than having to make two calls

- id/selector: yes. If an id is given (the default assumed parameter), then find the corresponding HTML element with that id (which would work for any shiny input widget). If the `selector` parameter is used instead, then click on the matching element. This can be useful when you want to click on non-shiny inputs, for example clicking on a link or on a row in a table or clicking a modal dismiss button that doesn't have an id or clicking on a button inside a widget that doesn't have a static id. Does that make sense to you?

- element is my way of saying "widget or any other html element" (I don't use the word widget myself because that implies only shiny inputs, and it also gets a bit confusing with htmlwidgets). It can be good to know if an HTML element is visible or not. The equivalent of `isElementDisplayed()` in selenium. It could be useful for example if you have a conditionalPanel. Doesn't matter if it's currently on the screen or if you need to scroll - I mean more if it's displayed or not.

**Comment by gaborcsardi** [comment]
> * app$update_value() - yes, I personally would find it much simpler to have a single function for it than having to make two calls

Yes, I wanted an `app$set_value` shortcut, too, just like we have `app$get_value`.

> * id/selector: yes. If an id is given (the default assumed parameter), then find the corresponding HTML element with that id (which would work for any shiny input widget). 

I didn't want to make this assumption, as I cannot ensure that it will hold in the future. Also, you can have two shiny widgets (sorry for the word) with the same id, one input and one output. So I think it can be confusing to allow widget ids and HTML ids as well.

> This can be useful when you want to click on non-shiny inputs, for example clicking on a link or on a row in a table or clicking a modal dismiss button that doesn't have an id or clicking on a button inside a widget that doesn't have a static id. Does that make sense to you?

Yes, makes complete sense. I think you can already do it, but you need to be a little more explicit. E.g. `app$find_element` finds a generic HTML element, and then `$click()` clicks on it. 

My intent was to conceptually separate shiny input/output widgets and HTML elements, even if there is of course a relationship between them. But maybe the Shiny user does not want to know the relationship. Advanced users can get HTML elements and do whatever they want with them. At least this is the idea.

> *  It can be good to know if an HTML element is visible or not.

I agree. The reason why this is not in `webdriver` is that the WebDriver protocol does not support it directly, frankly, I don't know why. See https://w3c.github.io/webdriver/webdriver-spec.html#list-of-endpoints

But I do want to support it, so I'll definitely write a method that uses their suggested approach. I'll open a new issue for it.

**Comment by gaborcsardi** [comment]
Sorry, right link: https://w3c.github.io/webdriver/webdriver-spec.html#element-displayedness

**Comment by daattali** [comment]
- id/selector: I've never tried having an input and output with the same id, but I guess you're right shiny won't complain about it explicitly... but it sounds very wrong, there should never ever be two elements on the same page that share an ID. Do you have an example where that was done?  I wouldn't shed a tear if there was a function that "penalizes" people for doing having multiple elements with the same id
:)


- The shiny widget id and the HTML id are always the same, are they not? If you have a `textInput("aaa", ...)` or a `plotOutput("bbb", ...)` then the corresponding HTML elements in the DOM will have ids "aaa" and "bbb".  Is there ever a case when that isn't true?

- click: I didn't realize you can already do that. In that case, that's fine. I wasn't sure what `find_element()` returns and what operations I can run on the returned object, and I didn't see any mention of a `click()` function anywhere, but I also didn't look super hard

- On a related note, I don't fully understand the difference between getting a widget and getting an element. I haven't looked at the implementation, but on an HTML level the only difference is that shiny inputs/outputs have an extra class. Does the return value from `find_widget()` support all the methods of `find_element()`, plus a few extra methods because we know it's an input/output? But they share the same basic methods that should be shared across any HTML element?

- displayedness: ah that's a shame. I haven't looked at their suggested approach, if it's a lot of work it might be better off to leave it as a v0.2 because it's definitely not a blocking feature

**Comment by gaborcsardi** [comment]
> * id/selector: I've never tried having an input and output with the same id, but I guess you're right shiny won't complain about it explicitly..

http://shiny.rstudio.com/gallery/widget-gallery.html See `#action` for example, but there is a lot them. But Joe was surprised to see this, too. :)

> * The shiny widget id and the HTML id are always the same, are they not?

I think that is always true currently. But I cannot pressure the Shiny devs to keep it like this. Already now, some widgets map to an HTML element that does not contain the full JS widget. IIRC the data table output is also kind of tricky. 

So in general, it seems like a good idea not to make that assumption, and I don't want (pure) Shiny users to think about HTML elements much.

> * On a related note, I don't fully understand the difference between getting a widget and getting an element. 

Technically a `widget` object contains the `element` as a member. The widget knows what kind of widget it is, e.g. a `sliderInput`. It knows how to get the value of the slider from the HTML dom. It knows how to set that value. 

An `element` is really just an HTML element, it has no idea about Shiny. This is why it is defined in the `webdriver` package.

You can get the element from the `widget` with `w$get_element()`, and then you can work on the element level. This is for advanced users that manipulate the app at the HTML/JS level.

> * displayedness: 

It does not seem to be a big deal to implement it, maybe phantom even has sg already, I don't remember. But I agree it is not a blocker.

**Comment by gaborcsardi** [comment]
Thanks for the great comments, btw!

**Comment by daattali** [comment]
- oh no, are there really that many cases of duplicated ids? That's really bad, trying to get an element by id has undefined behaviour in that case... at least the shiny examples won't have that soon :) https://github.com/rstudio/shiny-examples/pull/43  anyway, I still do think it's fine to do something that will break for people who duplicate an id. I've seen many questions on stackoverflow from people who don't understand why something breaks in shiny and the answer was because they were using the same id in different shiny widgets, so it's a good thing in my opinion to try to enforce that

- I agree most users shouldn't have to think about html elements, and just provide an id (aka the "name" of a shiny widget).  To clarify, this is what I mean: the signature of the function is `foo(id, selector)` and one of those two must be provided. Most users will simply call `foo("myinput")` or `foo("myoutput")`, but an advanced user can instead call `foo(selector = ".parent .child")`.  If you don't think that makes sense, then ok, I just wanted to make sure what I thought is clear

- Ah, now I understand what `find_element()` returns, because the docs for `w$get_element()` mention it. Cool.

- since you mention that widget objects know how to get/set their values, I'm just wondering: did you implement that logic manually, or are you using shiny's getvalue and setvalue?

- thanks for entertaining all my ideas and not getting offended at my comments :)

**Comment by gaborcsardi** [comment]
> * oh no, are there really that many cases of duplicated ids? ...  so it's a good thing in my opinion to try to enforce that

Good idea! We could just check the HTML source after the app starts up and give warnings (or errors?) for such cases. Super easy to do.

> * the signature of the function is foo(id, selector) and one of those two must be provided. 

I think this makes a lot of sense, but you can already do it easily, although the syntax is more verbose. Sg. like `$find_widget("id").get_element().find_element(".parent .child")`

The search in the last `find_element` will start from the HTML element of the widget. I kind of like the explicit `$get_element()` because that is a clear sign that you are working on the HTML level from then on.

> * because the docs for w$get_element() mention it. 

Sorry, the docs are crap. I still have a biggish problem to think about regarding more complex updates, and then I'll really start writing docs.

> * since you mention that widget objects know how to get/set their values, I'm just wondering: did you implement that logic manually, or are you using shiny's getvalue and setvalue?

It is manual. I tried not to look at the Shiny code at all. I really need to treat Shiny as a black box.

**Comment by daattali** [comment]
- I like that you credited your idea to me. Sure, that was my idea! I wasn't thinking that shinytest should do that because it feels like it's not shinytest's job to be so judgy - it's meant to test, not to give criticism. But sure, could be a useful side benefit, I'm not opposed to throwing a warning for that.  Definitely not an error though, since it's not an unrecoverable error and the user never really asked us to validate.....

- When I first talked about the id/selector thing, I didn't realize it was possible to select an element with CSS and to perform actions on any element. So it doesn't matter as much now.  (I think I personally would just use `find_element("#id .parent .child")` to save myself a lot of typing).  

- I agree that shiny should be treated as a blackbox in general, but I think that because of that it **would** be a good idea to let shiny do the value getting/setting instead of trying to fiddle with it manually. My main concern is that shiny has some specific logic implemented in javascript (eg https://github.com/rstudio/shiny/blob/master/srcjs/input_binding_number.js#L6-L17) for getting/setting values for each type of input, and if shinytest implements that logic independently, then there's a good chance it won't match. Which means that using shinytest's `get_value()` might give a different result than `input$` in shiny. Issue #24 is a direct result of me trying to prove this

**Comment by gaborcsardi** [comment]
> * When I first talked about the id/selector thing, I didn't realize it was possible to select an element with CSS and to perform actions on any element. So it doesn't matter as much now. (I think I personally would just use find_element("#id .parent .child") to save myself a lot of typing).

Yeah, you only need the longer form if you want to start searching from the element of the widget. `app$find_element` searches from the beginning.

> * I agree that shiny should be treated as a blackbox in general, but I think that because of that it would be a good idea to let shiny do the value getting/setting instead of trying to fiddle with it manually.

Agreed. I think it depends if you do `get_value` or `set_value`. 

For `get_value()`, I agree with you completely, and I should probably use the shiny js code. I'll look into that. #27

For `set_value()`, the more general question is whether we want to faithfully emulate a user or not. If yes, then I don't need any JS code, I just click on things, and send keyboard input. This could be harder to implement, and my `set_value` methods are a mix currently. I am not sure if it is the right approach, though.

**Comment by daattali** [comment]
You're right about `set_value()`, I didn't think of it that way. In Shiny, setting a value should do some input sanitization, but in shinytests you should forward the exact value that you were given onto the app. 

Whoo I think we're done the discussion on this issue! One issue down, 10 more were spawned...

**Comment by gaborcsardi** [comment]
I opened #28 for the `set_value()` approach. 

Can we close this issue now? :)

**Comment by DavidPatShuiFong** [comment]
> 
> I played with shinytest for a bit and it looks very promising, works well so far with the basic stuff I tried testing. Just a few more function ideas that I think could be useful:
> 
>     * app$update_value(id, value)
> 
>     * app$click(id/selector)
> 

For the sake of those who are part-time `R/shiny` users, and even more part-time `Javascript` users, here is a sample Javascript code for 'clicking' a widget which has an ID, but wasn't created using a standard technique. In my case, I created a 'custom-widget' inside a DT datatable, and that widget was not accessible with the standard `setInputs`.

For a widget named `addOne_1` :

```{r}
app$executeScript('document.getElementById("addOne_1").click()')
```

I defined the widget's name, but checked by inspecting the Element in the running Shiny app

```
<button id="addOne_1" type="button" class="btn btn-default action-button" onclick="Shiny.setInputValue(&quot;select_button&quot;, this.id, {priority: &quot;event&quot;})">+1</button>
```
