### ISSUE TITLE
Idea: list all inputs and outputs that are available in the app

### ISSUE THREAD

**Issue by daattali** [MangoTheCat/shinytest#22]
I can't decide if this is a good idea or if it's useless. I just started running shinytest on an app and I was trying to play with it in the console, but I forgot what IDs I need to use. Instead of having to look back at the source code, I wanted to type something like `app$list_inputs()`

Thoughts?

**Comment by gaborcsardi** [comment]
Definitely a good idea. One for inputs, one for outputs.

**Comment by gaborcsardi** [comment]
Was added in 6b8b4495d3ded3c21571b4ee311a803a0cb09fb9, just forgot to close this issue.
