### ISSUE TITLE
Numeric input doesn't recover from receiving bad input

### ISSUE THREAD

**Issue by daattali** [MangoTheCat/shinytest#24]
Using this shiny app:

```
library(shiny)
ui <- fluidPage(
  numericInput('num', "num", "5")
)

server <- function(input, output, session) {
  observe(cat(input$num))
}

shinyApp(ui = ui, server = server)
```

If I set the value of `num` to a bad value (not a number), and then set it to a valid number, the input still returns an `NA` value.

```
shinyapp$new(path = ".")$find_widget("num")$set_value("bogus")$set_value("8")$get_value()
```

If you take a screenshot, you'll see that the actual text inside the input is "bogus8", which means that the second "set_value" didn't actually replace the previous value

It's very possible that other inputs have similar issues, this is the first input I tried breaking

**Comment by gaborcsardi** [comment]
WTAL, thanks!

**Comment by gaborcsardi** [comment]
Is it OK if we give an error for bogus values?

**Comment by gaborcsardi** [comment]
Actually, no error is needed. THe Shiny get/set methods will just handle this.
