### ISSUE TITLE
Should check for duplicate IDs and give some sort of error

### ISSUE THREAD

**Issue by wch** [MangoTheCat/shinytest#54]
It would be nice to check for duplicate IDs, though I'm not sure when the right time would be to do the check, or how/when to signal an error.

Finding duplicates is simple. This is some code from: http://stackoverflow.com/a/509965/412655. I've added some code for timing as well.

```js
t0 = new Date();
$('[id]').each(function(){
  var ids = $('[id="'+this.id+'"]');
  if(ids.length>1 && ids[0]==this)
    console.warn('Multiple IDs #'+this.id);
});
t1 = new Date();
console.log(t1-t0);
```

Running on the widget gallery app takes between 1 and 3 ms on my computer (in Chrome), so it's pretty fast: https://gallery.shinyapps.io/081-widgets-gallery/

It's possible that this should just be in Shiny, though.

**Comment by gaborcsardi** [comment]
Good idea! But we are actually already doing this. :) 

Here:
https://github.com/MangoTheCat/shinytest/blob/fe32c21ccb9341319947b7558a7e26bd74ef5b8a/R/app.R#L349
and it uses this JS:
https://github.com/MangoTheCat/shinytest/blob/fe32c21ccb9341319947b7558a7e26bd74ef5b8a/inst/js/shiny-tracer.js#L56-L64

We also have some test cases for it, so we'll see if it works in other browsers.

**Comment by wch** [comment]
Oh nice. It might make sense to have it automatically run this check (and possibly others) by default when testing an app.

**Comment by gaborcsardi** [comment]
It does run automatically, actually. :)
https://github.com/MangoTheCat/shinytest/blob/fe32c21ccb9341319947b7558a7e26bd74ef5b8a/R/initialize.R#L37

I like the idea of having a bunch of default checks.
