### ISSUE TITLE
shinyapp class should be renamed

### ISSUE THREAD

**Issue by wch** [MangoTheCat/shinytest#59]
The name `shinyapp` is pretty close to `shinyApp`, which could lead to confusion. Maybe it could be `shinytestApp`?

**Comment by gaborcsardi** [comment]
:+1: As we discussed once, it is not really a shiny app, more a connection to it... so how about something completely different. Like `shinyDriver` or something along this line?

**Comment by wch** [comment]
Sure, `shinyDriver` sounds good to me.

**Comment by gaborcsardi** [comment]
OK. It would also make sense to convert everything to camelCase then? I should have done that from the beginning, sorry about that.

Anyway, just saying that it would be fine with me.

**Comment by wch** [comment]
I think my convention for R6 classes is to use camel case with the first letter capitalized (CamelCase), if that's OK with you.

**Comment by gaborcsardi** [comment]
Sure, that's fine. It should have been like that in the first place.

How about method names? Isn't it messy to have snake_cased method names then? AFAICT everything in Shiny is camelCase....

**Comment by gaborcsardi** [comment]
Anyway, if you prefer camelCase method names, I'll have some time to do that tomorrow....

**Comment by wch** [comment]
I don't have a strong preference, but camelCase method names do sound slightly better. I have a branch I've been working on that allows recording test events. Mind if I just merge that first, to avoid any conflicts?

**Comment by gaborcsardi** [comment]
Sure, np.

**Comment by wch** [comment]
OK, I merged it, so feel free to rename things.

**Comment by gaborcsardi** [comment]
OK, although my day is almost over, so it might be only next week. :/

**Comment by wch** [comment]
This was closed by #62.
