### ISSUE TITLE
shiny::runApp() does not have an argument "test.mode"

### ISSUE THREAD

**Issue by dbusbridge** [MangoTheCat/shinytest#60]
When running the following:

```{r}
library(shinytest)

app <- shinyapp$new("shiny-examples/050-kmeans-example")
```

I get the following error:

```
Error in app_start_shiny(self, private, path) : 
  Cannot find shiny port number. Error: Error in shiny::runApp("shiny-examples/050-kmeans-example", test.mode = TRUE) :unused argument (test.mode = TRUE)Execution halted
```

I belive this is caused by line 4 of the function ```shinytest:::app_start_shiny()``` :

```
runApp('%s', test.mode=TRUE)"), libpath, path)
```

which refers to a test mode. In the [current version of the shiny function](https://github.com/rstudio/shiny/blob/bc4dcee2b15303860ed5dd02f97500ceaf22ea29/R/server.R)  `runApp`() there is no argument `test.mode`. Unsure whether removing the corresponding argument from shinytest:::app_start_shiny()

```
runApp('%s', test.mode=TRUE)"), libpath, path) -> runApp('%s'), libpath, path)
```

since it might remove some *testing* nature that `shinytest` depends on. Is it possible the equivalent functionality [has been replaced with](https://rdrr.io/cran/shiny/man/exportTestValues.html) `options(shiny.testmode = TRUE)`?

Cheers!

**Comment by gaborcsardi** [comment]
I think you need the `testmode-inject-js` branch: https://github.com/rstudio/shiny/blob/testmode-inject-js/R/server.R#L553

**Comment by gaborcsardi** [comment]
We should probably depend on that branch, @wch?

**Comment by dbusbridge** [comment]
Okay - I'll try switching branches.

**Comment by dbusbridge** [comment]
I can confirm that the following:

```
library(devtools)

remove.packages("shiny", lib="~/R/x86_64-pc-linux-gnu-library/3.3")

devtools::install_git(url = "https://github.com/rstudio/shiny.git", 
                      branch = "testmode-inject-js")

library(shinytest)

app <- shinyapp$new("shiny-examples/050-kmeans-example")
```

Did not result in my previous error - loading a shiny app *without* a correct path results in the same error, leading me to believe this is the correct solution.

I now find a different error:

```
No encoding supplied: defaulting to UTF-8.
Error: Argument 'txt' must be a JSON string, URL or file.
```

which I will attempt to solve, otherwise I will raise a new issue.

Cheers! dan

**Comment by wch** [comment]
We'll probably merge that branch into Shiny's master branch today.

@dbusbridge, things are in a transitional state right now, so some stuff might be broken. :( I just pushed some commits to both shiny (in the branch) and shinytest which hopefully will make your error go away, but let me know if you still have problems.
